org.gradle.jvmargs=-Xmx1024M -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
android.nonTransitiveRClass=true
markwonVersion=4.6.2
ndkVersion=29.0.14206865
targetSdkVersion=36
minSdkVersion=21
compileSdkVersion=36
android.enableJetifier=true
app.versionCode=1
app.versionName=0.0.1_0

# NDK / native build knobs
# Corrected ABI for 64-bit ARM phone architectures
aurora.abiFilters=arm64-v8a